 /******************************************************************************
  * @file       USER/sound_list.h
  * @author  cjw
  * @date     2016.2.28
  * @brief     This file contains the define of sound list.
  ******************************************************************************/
#ifndef __SOUND_LIST_H
#define __SOUND_LIST_H

#define ZERO      1
#define ONE       2
#define TWO       3
#define THREE     4
#define FOUR      5
#define FIVE      6
#define SIX       7
#define SEVEN     8
#define EIGHT     9
#define NINE      10
#define TEN       11
#define ELEVEN    12
#define TWELVE    13
#define THIRTEEN  14
#define FOURTEEN  15
#define FIFTEEN   16
#define SIXTEEN   17
#define SEVENTEEN 18
#define EIGHTEEN  19
#define NINETEEN  20
#define TWENTY    21
#define THIRTY    22
#define FORTY     23
#define FIFTY     24
#define SIXTY     25
#define SEVENTY   26
#define EIGHTY    27
#define NINETTY   28
#define HUNDRED   29
#define AND       30
#define THOUSAND  31

#define ZIMU_A   33
#define ZIMU_B   34
#define ZIMU_C   35
#define ZIMU_D   36
#define ZIMU_E   37
#define ZIMU_F   38
#define ZIMU_G   39
#define ZIMU_H   40
#define ZIMU_I   41
#define ZIMU_J   42
#define ZIMU_K   43
#define ZIMU_L   44
#define ZIMU_M   45
#define ZIMU_N   46
#define ZIMU_O   47
#define ZIMU_P   48
#define ZIMU_Q   49
#define ZIMU_R   50
#define ZIMU_S   51
#define ZIMU_T   52
#define ZIMU_U   53
#define ZIMU_V   54
#define ZIMU_W   55
#define ZIMU_X   56
#define ZIMU_Y   57
#define ZIMU_Z   58

//#define BAOJING   59
#define YINGYUEYI 60
#define YINGYUEER 61
#define DINGDONG  62
#define QING      63
#define DAO       64
#define GUITAI    65
#define QUXIAO    66
#define HUJIAO    67
#define JIUSHUI   68
#define JIEZHANG  69
#define MAIDANG   70
#define DIANDANG  71
#define JIASHUI   72
#define TIANDIAN  73
#define SHIYING   74
#define FUWU      75
#define PIJIU     76
#define JIU       77
#define CUFANG    78
#define CUSHI     79
#define BATAI     80
#define BANGZHU   81
#define YISHENG   82
#define HUSHI     83
#define ANMO      84
#define ZHILIAO   85
#define QIANTAI   86
#define BAOJIE    87
#define BANGONG   88
#define BAZHEN    89
#define HUANYAO   90
#define SHUYE     91
#define JINJI     92
#define JIASHI    93
#define QINGJIE   94
#define GUANLI    95
#define WEIXIU    96
#define GUZHANG   97
#define ZHUXI     98
#define ZHUREN    99
#define LICAI     100
#define SHOUQUAN  101
#define ANQUAN    102
#define BAOAN     103
#define BAOJING   104
#define HAO       105
#define FANG      106
#define CHUANG    107
#define ZHUO      108
#define LOU       109
#define DENGHOU   110
#define CUNCHUSHEZHI   111
#define SHANGCHUSHEZHI 112  /*…æ≥˝…Ë÷√*/
#define XIANSHISHEZHI  113
#define XIAOHAOSHEZHI  114
#define XUNHUANSHEZHI  115
#define YUYINSHEZHI    116
#define JIANPANSHEZHI 117
#define ANJIANSHEZHI   118
#define HUIFUSHEZHI    119
#define DI			   120
#define CHENGGONG      121
#define SHIBAI         122
#define CHUSHIHUA      123

#define QUXIAO_1  51
#define BAOJING_1 52

#endif    /* __SOUND_LIST_H */
